### ISSUE TITLE
`rSharp_create_domain` should return a flag

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/rSharp#117] opened 2024-03-15 11:11 UTC
Loading assembly might throw an unhandled exception, which crashes R.

**Comment by rwmcintosh** [comment] 2024-03-15 11:19
What branch are you working in?
Seems like that should be part of the issue #53 which has been worked on in #112

**Comment by rwmcintosh** [comment] 2024-03-15 11:19
But not yet merged

**Comment by PavelBal** [comment] 2024-03-15 11:29
Yes working on that branch.

**Comment by rwmcintosh** [comment] 2024-03-15 12:00
Ok, when you can reproduce let's see. I expect the title will have to change somehow because we are catching exceptions and returning flags from C# to C++ and then C++ is returning a meaningful SEXP based on the flag.

**Comment by PavelBal** [comment] 2024-03-15 13:53
- Throw an error if `dotnetlib_path` is NULL

**Comment by rwmcintosh** [comment] 2024-03-15 15:18
This came up through a series of unfortunate events, but anyway, if a user does not call rsharp_create_domain, but calls other methods, the exception would happen and we should not crash R process in that event.

**Closed** 2024-04-16 07:53 UTC
